# Default values for experiment
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Logging (quiet will hide flux setup)
logging:
  quiet: true

experiment:
  iterations: 1
  # num_threads: 3
  # cores_per_task: 3
  nodes: 1
  tasks: 2

env:
  app: "gromacs"

monitor: {}

gromacs:
  binary: gmx_mpi
  ntomp: 1
  tpr: reference_s.tpr

minicluster:
  # Container image
  image: ghcr.io/converged-computing/gromacs:ubuntu2204
  
  # Interactive MiniCluster?
  interactive: false

  # Number of NVIDIA gpus
  gpus: 0
  
  # MiniCluster size
  size: 1
  
  # Add flux on the fly (set to false if Flux is already in the container)
  addFlux: false
  workdir: /opt/gromacs-2024.2/build/tests/regressiontests-2024.2/complex/argon
