# Default values for experiment
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Logging (quiet will hide flux setup)
logging:
  quiet: true

experiment:
  iterations: 1
  # num_threads: 3
  # cores_per_task: 3
  nodes: 1
  tasks: 2

env:
  app: single-node

minicluster:
  # Container image
  image: "ghcr.io/converged-computing/metric-single-node:cpu-zen4"

  # This needs priviledged
  privileged: true

  # Interactive MiniCluster?
  interactive: false
  
  # MiniCluster size
  size: 1
  
  # Minicluster tasks
  tasks: 8

  # Add flux on the fly (set to false if Flux is already in the container)
  addFlux: false
