# Default values for experiment
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Logging (quiet will hide flux setup)
logging:
  quiet: true

monitor: {}

experiment:
  iterations: 1
  # num_threads: 3
  # cores_per_task: 3
  nodes: 1
  tasks: 2
  
env:
  app: osu

osu:
  # All the binaries for point to point, collective, etc. are under "mpi"
  binary: /opt/osu-benchmark/build.openmpi/mpi/pt2pt/osu_latency

minicluster:
  # Container image
  image: ghcr.io/converged-computing/osu-benchmarks:ubuntu2204

  # Interactive MiniCluster?
  interactive: false
  
  # MiniCluster size
  size: 1
  
  # Number of NVIDIA gpus
  gpus: 0

  # Add flux on the fly (set to false if Flux is already in the container)
  addFlux: false
