# Default values for experiment
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Logging (quiet will hide flux setup)
logging:
  quiet: true

experiment:
  iterations: 1
  # num_threads: 3
  # cores_per_task: 3
  nodes: 1
  tasks: 2

env:
  app: "qmcpack"

qmcpack:
  binary: qmcpack
  xml: NiO-fcc-S8-dmc-strongscale.xml

minicluster:
  # Container image
  image: ghcr.io/converged-computing/qmcpack:ubuntu2204

  # Interactive MiniCluster?
  interactive: false

  # Number of NVIDIA gpus
  gpus: 0
  
  # MiniCluster size
  size: 1
  workdir: /coral2/NiO/dmc-a32-e384-batched_driver-DU32/

  commands_init: ". /opt/spack-environment/spack/share/spack/setup-env.sh && spack env activate /opt/spack-environment; sed -i 's/total_walkers\">128/total_walkers\">5632/g' /coral2/NiO/dmc-a32-e384-batched_driver-DU32/NiO-fcc-S8-dmc-strongscale.xml"
  
  # Add flux on the fly (set to false if Flux is already in the container)
  addFlux: false
