# Default values for experiment
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Logging (quiet will hide flux setup)
logging:
  quiet: true

experiment:
  iterations: 1
  # num_threads: 3
  # cores_per_task: 3
  nodes: 1
  tasks: 2

env:
  app: "netmark"

# sage: netmark.x [options]
# -w <warmups> : number of warmups
# -t <trials> : number of trials
# -c <send-recv-cycles> : number of send-recv cycles
# -b <msg size in B> : message size in bytes
# -s: store each trial flag

netmark:
  binary: netmark
  warmups: 10
  trials: 20
  sendReceiveCycles: 100
  messageSizeBytes: 0
  storeTrials: true

minicluster:
  # Container image
  image: "ghcr.io/converged-computing/netmark:latest"

  # Interactive MiniCluster?
  interactive: false

  # working directory we can copy results from
  workdir: /results/netmark
  
  # Number of NVIDIA gpus
  gpus: 0
  
  # MiniCluster size
  size: 1
  
  # Add flux on the fly (set to false if Flux is already in the container)
  addFlux: true
