# Default values for experiment
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Logging (quiet will hide flux setup)
logging:
  quiet: true

experiment:
  iterations: 1
  # num_threads: 3
  # cores_per_task: 3
  nodes: 1
  tasks: 2

monitor: {}

env:
  app: "smilei"
  example: benchmarks/tst2d_v_o2_multiphoton_Breit_Wheeler.py
  
smilei:
  binary: smilei
  # For shared, local data

minicluster:
  # Container image
  image: "ghcr.io/converged-computing/smilei:ubuntu2404"

  # Interactive MiniCluster?
  interactive: false

  # Number of NVIDIA gpus
  gpus: 0
  workdir: /opt/smilei
  
  # MiniCluster size
  size: 1
  
  # Add flux on the fly (set to false if Flux is already in the container)
  addFlux: true
