# Default values for experiment
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Logging (quiet will hide flux setup)
logging:
  quiet: true

experiment:
  iterations: 1
  # num_threads: 3
  # cores_per_task: 3
  nodes: 1
  tasks: 2

monitor: {}

env:
  app: "gamess"

gamess:
  binary: rimp2-serial
  # https://github.com/jkwack/GAMESS_RI-MP2_MiniApp
  data: /opt/data/benz.kern

minicluster:
  # Container image
  image: "ghcr.io/converged-computing/gamess-ri-mp2-miniapp:ubuntu2204"

  # Interactive MiniCluster?
  interactive: false

  # Number of NVIDIA gpus
  gpus: 0
  
  # MiniCluster size
  size: 1
  
  # Add flux on the fly (set to false if Flux is already in the container)
  addFlux: true
  
  # Logic to source the spack environment (needed for the default container)
  commands_init: 
    - . /opt/spack/share/spack/setup-env.sh 
    - spack load gamess-ri-mp2-miniapp
