# Default values for experiment
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Logging (quiet will hide flux setup)
logging:
  quiet: true

experiment:
  iterations: 1
  # num_threads: 3
  # cores_per_task: 3
  nodes: 1
  tasks: 2

monitor: {}

env:
  app: "hpl"

hpl:  
  binary: xhpl

minicluster:
  # Container image
  image: "ghcr.io/converged-computing/hpl:ubuntu2204"

  # Interactive MiniCluster?
  interactive: false

  # Number of NVIDIA gpus
  gpus: 0
  
  # MiniCluster size
  size: 1
  workdir: /opt/hpl
  
  # Add flux on the fly (set to false if Flux is already in the container)
  addFlux: false
  commands_init: ". /opt/spack-environment/spack/share/spack/setup-env.sh && spack env activate /opt/spack-environment"  
