# Default values for experiment
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Logging (quiet will hide flux setup)
logging:
  quiet: true

experiment:
  iterations: 1
  # num_threads: 3
  # cores_per_task: 3
  nodes: 1
  tasks: 2

env:
  app: "havoc"
  
havoc:
  binary: havoqgt
  # For shared, local data

minicluster:
  # Container image
  image: "ghcr.io/rse-ops/havoqgt:flux"

  # Interactive MiniCluster?
  interactive: false

  # Number of NVIDIA gpus
  gpus: 0
  
  # MiniCluster size
  size: 1
  
  # Add flux on the fly (set to false if Flux is already in the container)
  addFlux: true
  commands_init: flux run -n $(nproc) src/generate_rmat -s 17 -o outgraph

