# Default values for experiment
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Logging (quiet will hide flux setup)
logging:
  quiet: true

experiment:
  iterations: 1
  # num_threads: 3
  # cores_per_task: 3
  nodes: 1
  tasks: 2

env:
  app: "bdas"

bdas:
  binary: bdas
  filename: testfile
  # Other files in this directory, both take rows/cols
  # kmeans.r  princomp.r  svm.r  utils.r
  benchmark: /opt/bdas/benchmarks/r/princomp.r
  rows: 250
  cols: 50

minicluster:
  # Container image
  image: "ghcr.io/converged-computing/metric-bdas:latest"

  # Interactive MiniCluster?
  interactive: false

  # Number of NVIDIA gpus
  gpus: 0
  
  workdir: /opt/bdas/benchmarks/r

  # MiniCluster size
  size: 1
    
  # Add flux on the fly (set to false if Flux is already in the container)
  addFlux: true
