# Default values for experiment
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Logging (quiet will hide flux setup)
logging:
  quiet: true

experiment:
  iterations: 1
  # num_threads: 3
  # cores_per_task: 3
  nodes: 1
  tasks: 2

env:
  app: "gpcnet"

monitor: {}

# Run example at 64 nodes of BDW 18 parts (2 per node) fully packed on a Cray/ALPS system:
# aprun -n 2304 -N 36 ./network_test
# aprun -n 2304 -N 36 ./network_load_test

gpcnet:  
  binary: network_test
  # For shared, local data

minicluster:
  # Container image
  image: ghcr.io/converged-computing/gpcnet:2204

  # Interactive MiniCluster?
  interactive: false

  # Number of NVIDIA gpus
  gpus: 0
  workdir: /opt/gpcnet
  
  # MiniCluster size
  size: 1
  
  # Add flux on the fly (set to false if Flux is already in the container)
  addFlux: false
  commands_init:
    - . /opt/spack-environment/spack/share/spack/setup-env.sh
    - spack env activate /opt/spack-environment/

