# Default values for experiment
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Logging (quiet will hide flux setup)
logging:
  quiet: true

experiment:
  iterations: 1
  # num_threads: 3
  # cores_per_task: 3
  nodes: 1
  tasks: 2
  # Num processors must be a cube of an integer (1, 8, 27, ...)

env:
  app: lulesh
  # flux run -N2 -n 125 -o cpu-affinity=per-task -o gpu-affinity=off lulesh -i 100 -s 50 -r 11 -b 1 -c 1

lulesh:
  binary: lulesh
  iterations: 100
  size: 40
  regions: 11
  balance: 1 
  cost: 1 
  # numfiles

minicluster:
  # Container image
  image: "ghcr.io/rse-ops/lulesh:flux"

  # Interactive MiniCluster?
  interactive: false

  # Number of NVIDIA gpus
  gpus: 0
  
  # MiniCluster size
  size: 1
  
  # Add flux on the fly (set to false if Flux is already in the container)
  addFlux: false
