{{- define "kubeflow-template.pytorch-job" -}}
apiVersion: "kubeflow.org/v1"
kind: PyTorchJob
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  pytorchReplicaSpecs:
    Master:
      replicas: 1
      restartPolicy:  {{ default "OnFailure" .Values.master.restartPolicy }}
      template:
        spec:
          containers:
            - name: pytorch
              image: {{ .Values.master.image }}
              imagePullPolicy: {{ default "IfNotPresent" .Values.master.imagePullPolicy }}
              resources:
                limits:
                  nvidia.com/gpu: {{ default 1 .Values.master.gpus }}
              command:
                - "/bin/bash"
                - "-c"
                - "{{ .Values.master.command }}"
    Worker:
      replicas: {{ .Values.worker.replicas }}
      restartPolicy: {{ .Values.worker.restartPolicy }}
      template:
        spec:
          containers:
            - name: pytorch
              image: {{ .Values.worker.image }}
              resources:
                limits:
                  nvidia.com/gpu: {{ .Values.worker.gpus }}
              imagePullPolicy: {{ .Values.worker.imagePullPolicy }}
              command:
                - "/bin/bash"
                - "-c"
                - "{{ .Values.worker.command }}"
{{ end }}
