# Default values for experiment
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Logging (quiet will hide flux setup)
logging:
  quiet: true

env:
  app: minife

experiment:
  iterations: 1
  # num_threads: 3
  # cores_per_task: 3
  nodes: 1
  tasks: 2
  
monitor: {}

minife:
  binary: miniFE.x
  nx: 230
  ny: 230
  nz: 230
  use_locking: 1
  elem_group_size: 10
  use_elem_mat_fields: 300  
  verify_solution: 0

minicluster:
  # Container image
  image: ghcr.io/converged-computing/minife:ubuntu2204

  # Interactive MiniCluster?
  interactive: false
  
  # MiniCluster size
  size: 1
  
  # Number of NVIDIA gpus
  gpus: 0

  # Add flux on the fly (set to false if Flux is already in the container)
  addFlux: false
