# Default values for experiment
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Logging (quiet will hide flux setup)
logging:
  quiet: true

experiment:
  iterations: 1
  gpu_affinity: per-task
  # num_threads: 3
  # cores_per_task: 3
  nodes: 1
  tasks: 2

env:
  app: "nccl-tests"

flux:
  image: ghcr.io/converged-computing/flux-view-ubuntu:tag-jammy

nccl:
  binary: ./nccl-tests/build/all_reduce_perf
  begin: 8
  end: 8G
  f: 2
  g: 1

# flux run -n 2 -N 2 -g 1 ./nccl-tests/build/all_reduce_perf -b 8 -e 8G -f 2 -g 1

minicluster:
  # Container image
  image: "ghcr.io/converged-computing/metric-nccl-tests:flux-gpu-12.4.1"

  # Interactive MiniCluster?
  interactive: false

  # Number of NVIDIA gpus
  gpus: 1
  
  # MiniCluster size
  size: 1
  
  # Add flux on the fly (set to false if Flux is already in the container)
  addFlux: false
