name: ramble-helm

on:
  pull_request: {}
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        app: [lammps]        
    name: Prepare charts
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - uses: actions/setup-go@v3
      with:
        go-version: ^1.22
    - name: GHCR Login
      if: (github.event_name != 'pull_request')
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Install Helm
      run: |
        export HELM_EXPERIMENTAL_OCI=1
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash        
      
    - name: Login to Helm
      if: (github.event_name != 'pull_request')
      env:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        app: ${{ matrix.app }}
      run: |
        echo "${password}" | helm registry login -u ${username} --password-stdin ${registry} 
        PKG_RESPONSE=$(helm package ./$app)
        echo "$PKG_RESPONSE"
        CHART_TAR_GZ=$(basename "$PKG_RESPONSE") 
        helm push "$CHART_TAR_GZ" oci://ghcr.io/converged-computing/flux-apps-helm:${app}
