{{- define "base-template.flux-minicluster" -}}
apiVersion: flux-framework.org/v1alpha2
kind: MiniCluster
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  size: {{ default 1 .Values.minicluster.size }}
  {{ if .Values.minicluster.interactive }}interactive: true {{ end }}
  {{ if .Values.minicluster.tasks }}tasks: {{ .Values.minicluster.tasks }}{{ end }}

  logging:
    quiet: {{ if .Values.logging.quiet }}true{{ else }}false{{ end }}

  # This disables installing flux via the view
  flux:
    container:
      disable: {{ if .Values.minicluster.addFlux }}false{{ else }}true{{ end }}

  containers:
  - image: "{{ default "ghcr.io/converged-computing/metric-lammps-cpu:zen4-reax" .Values.minicluster.image }}"
    command: /bin/bash /tmp/run_${app}.sh
    launcher: true
    securityContext:
      privileged: {{ if .Values.minicluster.privileged }}true{{ else }}false{{ end }}
    commands:
      {{ if .Values.minicluster.commands_init }}init: {{ .Values.minicluster.commands_init }}{{ end }}
      post: |
        cat /tmp/${app}.out
        {{- if .Values.minicluster.commands_finish }}{{- range $k, $v := .Values.minicluster.commands_finish }}
          {{ . | toYaml | indent 4 | trim }}
        {{- end }}{{- end }}

      pre: |
         cat <<EOF >> /tmp/run_${app}.sh
         #!/bin/bash
         set -euo pipefail
         mkdir -p /tmp/output
         flux resource list
         for i in {1..{{ default 1 .Values.experiment.iterations}}}
         do
           flux run --setattr=user.study_id=$app-iter-\$i -N{{ if .Values.experiment.nodes }}{{ .Values.experiment.nodes }}{{ else }}1{{ end }} {{ if .Values.experiment.tasks }}-n {{ .Values.experiment.tasks }}{{ end }} -o cpu-affinity={{ default "per-task" .Values.experiment.cpu_affinity }} -o gpu-affinity={{ default "off" .Values.experiment.gpu_affinity }} {{ if .Values.experiment.run_threads }}--env OMP_NUM_THREADS={{ .Values.experiment.run_threads }}{{ end }} {{ if .Values.experiment.cores_per_task }}--cores-per-task {{ .Values.experiment.cores_per_task }}{{ end }} {{ if .Values.experiment.exclusive }}--exclusive{{ end }} ${apprun} >> /tmp/${app}.out
         done
         {{- if .Values.minicluster.commands_post }}{{- range $k, $v := .Values.minicluster.commands_post }}
           {{ . | toYaml | indent 4 | trim }}
         {{- end }}{{- end }}
         EOF
         cat /tmp/run_${app}.sh
{{ end }}
